[package]
name = "elmesque"
version = "0.0.3"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
description = "An attempt at porting Elm's incredibly useful, purely functional std graphics modules."
readme = "README.md"
keywords = ["elm", "graphics", "2d", "ui", "shape"]
license = "MIT"
repository = "https://github.com/mitchmindtree/elmesque.git"
homepage = "https://github.com/mitchmindtree/elmesque"



[dev-dependencies.pistoncore-glutin_window]
git = "https://github.com/PistonDevelopers/glutin_window.git"
version = "*"

[dev-dependencies.piston]
git = "https://github.com/PistonDevelopers/piston.git"
version = "*"

[dev-dependencies.shader_version]
git = "https://github.com/PistonDevelopers/shader_version"
#version = "*"

[dev-dependencies.piston-gfx_texture]
git = "https://github.com/PistonDevelopers/gfx_texture.git"
version = "*"

[dev-dependencies.gfx_device_gl]
git = "https://github.com/gfx-rs/gfx_device_gl.git"
version = "*"

[dev-dependencies.piston2d-gfx_graphics]
git = "https://github.com/PistonDevelopers/gfx_graphics.git"
version = "*"


[dependencies]
piston2d-graphics = "*"
num = "*"
vecmath = "*"
