[package]
name = "elmesque"
version = "0.0.3"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
description = "An attempt at porting Elm's incredibly useful, purely functional std graphics modules."
readme = "README.md"
keywords = ["elm", "graphics", "2d", "ui", "shape"]
license = "MIT"
repository = "https://github.com/mitchmindtree/elmesque.git"
homepage = "https://github.com/mitchmindtree/elmesque"

[dependencies.piston-gfx_texture]
git = "https://github.com/PistonDevelopers/gfx_texture.git"
version = "*"

[dependencies.gfx_device_gl]
git = "https://github.com/gfx-rs/gfx_device_gl.git"
version = "*"

[dependencies]
piston2d-graphics = "*"
vecmath = "*"
